# Generated by Django 3.2.3 on 2021-06-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210606_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcity',
            name='CONTACT_HISTORY',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapcity',
            name='accumulation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mapcity',
            name='new',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mapcity',
            name='related_gu',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapcity',
            name='sigungu_kr',
            field=models.CharField(db_column='sigungu_KR', max_length=200),
        ),
    ]
