# Generated by Django 3.2.3 on 2021-06-07 00:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20210606_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapcity',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
