# Generated by Django 3.2.3 on 2021-06-12 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_mapcity_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.IntegerField(default=0)),
                ('accumulation', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.mapcity')),
            ],
        ),
    ]
