# Generated by Django 3.2.3 on 2021-06-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='CountStatus',
        ),
    ]
