# Generated by Django 3.2.3 on 2021-06-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_rename_address_countstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countstatus',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
